### ISSUE TITLE
Override views carousel and accordion to work with Bootstrap 5.1

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago_subtheme#36]
# What?
Part of #24. A simple override of the views_bootstrap module templates using [this example](https://www.drupal.org/project/views_bootstrap/issues/3168271#comment-14161865).

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/archipelago_subtheme/commit/861d0affa4f19567f4a60bd67347a4727f0fdee4
@aksm we will have to override all other eventually too so please add a comment when you can to the more general Upgrade to bootstrap ISSUE with a link to the source of this overrides. All for 1.1.0! Thanks
